In [2]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.8.0+cpu
CUDA available: False


Tensors are a specialised structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.  
***A Tensor is a numerical container of arbitrary dimensions, and it is the core data structure that PyTorch operates on.***

## Tensor Initialisation


**Directly from data**:  
Tensors can be created directly from data. The data type is automatically inferred.

**From A Numpy Arrary**  
Tensors can be created from Numpy arrays (and vice versa).

**From Another Tensor**  
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

**with Random or Constant Values**  
```shape``` is a tuple of tensor dimensions. In the functions below, it determines the dimensionally of the output tensor.

## Tensor Attributes

In [48]:
tensor = torch.rand(2,3)
print(tensor)
print(f"Shape of Tensor: {tensor.shape}")
print(f"Datatype of Tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.4991, 0.1349, 0.9505],
        [0.4508, 0.6830, 0.3670]])
Shape of Tensor: torch.Size([2, 3])
Datatype of Tensor: torch.float32
Device tensor is stored on: cpu


Each of tensors can be run on the GPU.

**Standard Numpy-like Indexing and Slicing**  

**Joinining Tensors**  
You can use torch.cat to concatenate a sequence of tensors along a given dimensions.  
*NOTE*
1. The dimension you choose can have different lengths, because that is the one we are extending.
2. All the other dimensions must be the same, otherwise, it is ike trying to stack Lego blocks of different sizes and they will not fit.  

**torch.cat() VS torch.stack()**    
|Operation|Result|Shape|Characteristics|
|---------|------|-----|---------------|
|torch.cat([a,b], dim = 0)|[[1,2,3],[4,5,6]]|(2,3)|Concatenates along rows -> stacked vertically|
|torch.cat([a,b], dim=1)|[[1,2,3,4,5,6]]|(1,6)|Concatenates along columns -> stacjked horizontally|
torch.stack([a,b].dim=0)|[[[1,2,3]],[[4,5,6]]]|(2,1,3)|Creates a new dimension at the front -> 3D tensor|
|torch.stack([a,b], dim=1)|[[[1,2,3],[4,5,6]]]|(1,2,3)|Creates a new dimension in the middle -> 1 block of shape $(2 \times 3)$|

**Multiplying Tensors**  
1. Element-wise Product: tensor1* tensor2, tensor1.mul(tensor2)
2. Matrix multiplication: tensor11.matmul(tensor2), tensor1 @ tensor2

In [78]:
# matrix multiplication
tensor1 = torch.tensor([[1,2], [1,2]])    
tensor2 = torch.tensor([[1,2], [3,4]])
# method 1
tensor3 = tensor1 @ tensor2
# method 2
tensor4 = tensor1.matmul(tensor2)
print(tensor3)
print(tensor4)

tensor([[ 7, 10],
        [ 7, 10]])
tensor([[ 7, 10],
        [ 7, 10]])


In [87]:
tensor = torch.rand(5,5)
print(tensor)
tensor_add5 = tensor.add_(5)
print(tensor_add5)

tensor([[0.6919, 0.7100, 0.2123, 0.8367, 0.9037],
        [0.2508, 0.6395, 0.2129, 0.0154, 0.5361],
        [0.5801, 0.8836, 0.8760, 0.1594, 0.7700],
        [0.7479, 0.5176, 0.7220, 0.5189, 0.3494],
        [0.8948, 0.6106, 0.3327, 0.3970, 0.7814]])
tensor([[5.6919, 5.7100, 5.2123, 5.8367, 5.9037],
        [5.2508, 5.6395, 5.2129, 5.0154, 5.5361],
        [5.5801, 5.8836, 5.8760, 5.1594, 5.7700],
        [5.7479, 5.5176, 5.7220, 5.5189, 5.3494],
        [5.8948, 5.6106, 5.3327, 5.3970, 5.7814]])


In [94]:
tensor_new = torch.rand(5,5)
tensor.copy_(tensor_new) # using copy_ to change the original tensor
# the size of the tensor is the same as the original tensor

tensor([[0.0101, 0.9939, 0.5913, 0.6275, 0.1166],
        [0.1435, 0.4948, 0.6813, 0.6999, 0.7142],
        [0.2320, 0.6258, 0.4327, 0.4303, 0.9632],
        [0.8310, 0.0059, 0.4553, 0.0558, 0.1104],
        [0.5218, 0.7494, 0.9381, 0.4372, 0.4053]])

Tensors on the CPU can share their underlying memory locations, and changing one will change the other.

In [100]:
tensor1 =  torch.ones(5)
print(tensor1)
n_array = tensor1.numpy()
print(n_array)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [102]:
np.add(n_array, 1, out = n_array)
print(n_array)
print(tensor1)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.])


In [103]:
n_array = np.ones(5)
tensor1 = torch.from_numpy(n_array)
print(n_array)
print(tensor1)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [105]:
tensor1.add_(2)
print(n_array)
print(tensor1)

[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


```torch.autograd``` is PyTorch's automatic differentiation engine that powers neural network training.

## Example

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

3.6%

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\junqi.wu/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth


100.0%


In [ ]:
prediction = model(data)

In [109]:
loss = (prediction - labels).sum()
loss.backward()

In [110]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum = 0.9)

In [112]:
optim.step()