In [1]:
!pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu128

Looking in indexes: https://download.pytorch.org/whl/cu128



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import torch
print(torch.__version__)

2.8.0+cu128


# Initialising Tensor

In [15]:
# store the tensor on cuda (GPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],
                         dtype = torch.float32,
                         device = device,
                         requires_grad = True) # useful for autograd for backpropagation
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])


In [33]:
x1 = torch.empty(size = (3,3)) # the values is not zero but uninistialised data
print(x1)
x2 = torch.zeros(size = (3,3))
print(x2)
x3 = torch.ones(size = (3,3))
print(x3)
x4 = torch.rand(size = (3,3))
print(x4)
x5 = torch.eye(3,3) # identity matrics I
print(x5)
x6 = torch.arange(start = 0, end=10, step = 2)
print(x6)
x7 = torch.linspace(start = 0.1, end = 1, steps = 10)
print(x7)
x8 = torch.empty(size = (1,5)).normal_(mean = 0, std = 1)
print(x8)
x9 = torch.diag(torch.ones(3))
print(x9)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9072, 0.1718, 0.7274],
        [0.1371, 0.6723, 0.2226],
        [0.3290, 0.4328, 0.9129]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.8996, -0.3080,  2.7760, -0.3528, -0.3810]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# How to initialise and convert tensors to other types

In [44]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor.bool())
print(my_tensor.short()) # to int16 (use 2 bytes)
print(my_tensor.long()) # to int64 (use 8 bytes)
print(my_tensor.half()) # to float16
print(my_tensor.float()) # to float32
print(my_tensor.double()) # to float64


tensor([[True, True, True],
        [True, True, True]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


# Array to Tensor Conversion and Vice Versa

In [45]:
import numpy as np

In [49]:
np_arrary = np.zeros((5,5))
print(np_arrary)
tensor = torch.from_numpy(np_arrary)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Maths & Comparison Operations|

In [51]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

## Addition

In [55]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)
z2 = torch.add(x,y)
print(z2)
z3 = x + y
print(z3)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])


## Subtraction

In [57]:
z4 = x - y
print(z4)

tensor([-8, -6, -4])


## Division

In [60]:
z5 = torch.true_divide(x,y)
print(z5)

tensor([0.1111, 0.2500, 0.4286])


## Inplace Operations

In [62]:
t = torch.zeros(3)
t.add_(x)
print(t)
t += x
print(t)

tensor([1., 2., 3.])
tensor([2., 4., 6.])


## Exponentiation

In [64]:
z = x.pow(2)
print(z)
z = x ** 2
print(z)

tensor([1, 4, 9])
tensor([1, 4, 9])


## Simple Comparison

In [66]:
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


## Matrix Multiplication

In [70]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2)
print(x3)
x4 = x1.mm(x2)
print(x4)

tensor([[0.8912, 1.4679, 0.7802],
        [0.9840, 1.1380, 0.9983]])
tensor([[0.8912, 1.4679, 0.7802],
        [0.9840, 1.1380, 0.9983]])


## Matrix Exponentiation

In [71]:
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)
print(matrix_exp)

tensor([[0.0776, 0.9147, 0.5477, 0.6982, 0.5237],
        [0.5580, 0.8934, 0.5037, 0.0108, 0.6280],
        [0.3702, 0.9875, 0.2423, 0.4419, 0.6851],
        [0.3828, 0.4076, 0.8272, 0.4796, 0.3511],
        [0.5747, 0.7785, 0.8368, 0.9090, 0.1010]])


## Element Wise Multiplication

In [73]:
z = x * y
print(z)

tensor([ 9, 16, 21])


## Dot Product

In [74]:
z = torch.dot(x,y)
print(z)

tensor(46)


## Batch Matrix Multiplication

In [75]:
batch = 32
n = 10
m = 20
p = 30

In [76]:
tensor1 = torch.rand((batch,n,m))
print(tensor1)
tensor2 = torch.rand((batch,m,p))
print(tensor2)
out_bmm = torch.bmm(tensor1, tensor2) # batch, n, p

tensor([[[1.8625e-01, 5.4215e-01, 6.2484e-01,  ..., 9.1648e-01,
          2.5522e-01, 8.9167e-01],
         [2.5499e-01, 9.6767e-01, 6.1583e-01,  ..., 1.7615e-01,
          9.8343e-01, 6.9127e-01],
         [6.2983e-02, 8.8969e-01, 5.6680e-01,  ..., 5.4676e-01,
          9.5317e-01, 9.0713e-01],
         ...,
         [4.8452e-01, 1.9665e-01, 7.5685e-02,  ..., 1.6189e-01,
          3.6331e-01, 8.6274e-01],
         [7.7615e-01, 3.1569e-01, 2.5694e-01,  ..., 7.8023e-01,
          4.9753e-01, 3.6914e-01],
         [3.9223e-01, 7.8440e-01, 2.6954e-01,  ..., 8.6629e-01,
          8.3967e-01, 9.1223e-01]],

        [[8.3038e-01, 3.1680e-01, 8.9343e-02,  ..., 7.1499e-01,
          9.3580e-01, 6.5724e-01],
         [5.1857e-01, 7.8323e-01, 1.7766e-01,  ..., 8.9901e-01,
          4.9905e-01, 6.6645e-01],
         [3.0057e-01, 2.6418e-01, 3.1136e-01,  ..., 8.4469e-01,
          8.4964e-01, 6.5220e-01],
         ...,
         [4.5736e-01, 2.8167e-01, 8.8835e-01,  ..., 1.1818e-02,
          7.610

## Example of Broadcasting

In [81]:
x1 = torch.zeros((5,5))
print(x1)
x2 = torch.ones((1,5))
print(x2)
z = x1 - x2
print(z)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.]])
tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])


In [97]:
sum_x = torch.sum(x, dim = 0)
print(sum_x)
values, indices = torch.max(x, dim = 0)
print(values, indices)
abs_x = torch.abs(x)
print(abs_x)
z = torch.argmax(x, dim = 0)
print(z)
z = torch.argmin(x, dim = 0)
print(z)
mean_x = torch.mean(x.float(), dim = 0)
print(mean_x)
z = torch.eq(x,y) # check equal elements
print(z)
sorted_y, indices = torch.sort(y, dim = 0, descending = False)
print(sorted_y, indices)

z = torch.clamp(x, min = 0) # check values, if less than 0, then set to 0
print(z)
z = torch.clamp(x, max = 10) # check values, if greater than 10, then set to 10

tensor(6)
tensor(3) tensor(2)
tensor([1, 2, 3])
tensor(2)
tensor(0)
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
tensor([1, 2, 3])


In [100]:
x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
print(x)
z = torch.any(x)
print(z)
z = torch.all(x)
print(z)

tensor([ True, False,  True,  True,  True])
tensor(True)
tensor(False)


# Tensor Indexing

In [102]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [107]:
print(x[0]) # equal to x[0, :]
print(x[0].shape)
print(x[:,0])
print(x[2, 0:10])

tensor([0.5045, 0.7980, 0.5538, 0.5540, 0.7396, 0.2513, 0.0611, 0.1036, 0.0643,
        0.2271, 0.4901, 0.5595, 0.4429, 0.5795, 0.1324, 0.5222, 0.9868, 0.5989,
        0.5658, 0.4378, 0.0626, 0.3275, 0.5912, 0.7545, 0.1300])
torch.Size([25])
tensor([0.5045, 0.2490, 0.2900, 0.2584, 0.5073, 0.6994, 0.7863, 0.5568, 0.7735,
        0.6262])
tensor([0.2900, 0.9483, 0.0444, 0.5894, 0.8029, 0.8864, 0.9529, 0.7391, 0.7506,
        0.3428])


## Fancy Indexing

In [109]:
x = torch.arange(10) # tensor([0,1,2,3,4,5,6,7,8,9])
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [111]:
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols]) # first take (1,4), then take (0,0)
print(x[rows,cols].shape)


tensor([[0.0502, 0.5622, 0.3310, 0.4078, 0.0884],
        [0.5121, 0.9768, 0.3402, 0.8912, 0.4334],
        [0.0112, 0.6586, 0.8340, 0.2671, 0.5100]])
tensor([0.4334, 0.0502])
torch.Size([2])


## More Advanced Indexing

In [125]:
x = torch.arange(10)
print(x[(x<2)|(x>8)]) # or
print(x[(x<2)&(x>8)]) # and
print(x[x.remainder(2) == 0])
print(torch.where(x>5, x, x*2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel()) # number of elements

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


# Tensor Reshaping

In [128]:
x = torch.arange(9)
x_3x3 = x.view(3,3) # requires contiguous memory for origin tensor or may lead to error or weird result
print(x_3x3)
x_3x3 = x.reshape(3,3)  # works even if non-contiguous (may copy data to ensure reshape)
print(x_3x3)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [130]:
y = x_3x3.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [135]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2),dim=0))
print(torch.cat((x1,x2),dim=1))

tensor([[0.8305, 0.6043, 0.2036, 0.3169, 0.8887],
        [0.7409, 0.1171, 0.8144, 0.1459, 0.2566],
        [0.5619, 0.5990, 0.1177, 0.5488, 0.7997],
        [0.2202, 0.2468, 0.5815, 0.8445, 0.8680]])
tensor([[0.8305, 0.6043, 0.2036, 0.3169, 0.8887, 0.5619, 0.5990, 0.1177, 0.5488,
         0.7997],
        [0.7409, 0.1171, 0.8144, 0.1459, 0.2566, 0.2202, 0.2468, 0.5815, 0.8445,
         0.8680]])


In [138]:
print(x1.view(-1)) # flatten

tensor([0.8305, 0.6043, 0.2036, 0.3169, 0.8887, 0.7409, 0.1171, 0.8144, 0.1459,
        0.2566])


In [139]:
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [141]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [147]:
x = torch.arange(10)
print(x)
print(x.unsqueeze(0))
print(x.unsqueeze(1))
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print(torch.arange(10).unsqueeze(0).unsqueeze(1)) # 1 * 1 * 10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([1, 10])
torch.Size([10, 1])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [151]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x)
z = x.squeeze(1)
print(z)
z = z.squeeze(0)
print(z)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
